:PROPERTIES:
:ID:       7d87c81c-cbf4-4a19-8d34-17dde8e94ea3
:END:
#+title: Physics of Information
#+filetags: :moc: 
#+hugo_base_dir: /home/phihungnguyen/quartz 
#+hugo_section: QuantumInformation/Introduction
#+date: [2024-02-28 Wed]
#+hugo_lastmod: [2024-02-28 Wed]
#+hugo_tags: noexport
*Link*:  

* Information

There are some constraints on our ability to use and manipulate the information

For example:

1) Landauer's principle
   Erasure of information is a dissipative process (irreversible). By removing information, we are
   essentially creating an entropy $$\delta S=k \ln{2}$$
2) Reversible computation
   Logic gates that perform computation are typically irreversible. For example, the NAND gate
   $$(a, b) \rightarrow \neg (a \land b)$$
   We could see that one bit is erased from this process. A work is needed to operate the gate $$W = kT \ln 2$$.
   In theory, we can construct any computation using only reversible steps that preserve all the information (Toffolo) gate
   $$(a, b, c) \rightarrow (a, b, c \oplus a \land b)$$. However, the Landauer's principle in practice does not
   matter for engineering problem because we have overcome this limitation to even care about
3) Maxwell's demon
   A thought experiment by Maxwell that shows the erasure of information costs energy

* Quantum Information
INFORMATION IS PHYSICAL. Since the universe is fundamental quantum. What is better than representing them in quantum?

Why quantum information?

1) Classical information does not have true randomness.
2) Noncomutting observables cannot be observed simultaneously. Observing the system will disturb the system ie, getting information means
   changing the system
3) Quantum information cannot be copied with perfect fidelity (no cloning principle)
4) Quantum mechanics cannot be produced by any local hiddle variable


